# Generated by Django 3.1.7 on 2021-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=32)),
                ('address', models.TextField(max_length=500)),
                ('email', models.EmailField(max_length=100)),
                ('mobile', models.CharField(max_length=10)),
            ],
        ),
    ]
