# Generated by Django 3.1.7 on 2021-06-21 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='category',
        ),
    ]
