# Generated by Django 3.1.7 on 2021-06-21 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_orders_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
