# Generated by Django 3.1.7 on 2021-06-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.IntegerField(default=0),
        ),
    ]
